baseURL = 'https://example.org/'
languageCode = 'zh-tw'
DefaultContentLanguage = "zh"
title = "Eri24816's blog"
theme = 'lightbi-hugo'

[pagination]
    pagerSize = 18

summaryLength  = "30"



[Params]
    customCSS = ["custom.css"]
previewCardImagePlacement = "top"
quote = "希望在大學的壓力下不要丟失我的初衷。\n那就是：我喜愛這個世界，所以想以最 high level 的角度理解世界，幫各種我喜歡的東西建立模型。例如音樂生成模型、style transfer、物理模擬。"