baseURL = 'https://eri24816.tw/'
languageCode = 'zh-tw'
DefaultContentLanguage = "zh-TW"
title = "eri24816's blog"
theme = 'lightbi-hugo'

staticDir = ["content/static", "static"]

[pagination]
    pagerSize = 18

summaryLength  = "30"



[Params]
    customCSS = ["custom.css"]
previewCardImagePlacement = "top"
quote = "我想以最 high level 的角度理解世界，幫各種我喜歡的東西建立模型。例如音樂生成模型、style transfer、物理模擬。"

[languages]
  [languages.zh-TW]
    languageName = "繁體中文"
    contentDir = "content/zh"
    weight = 1

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2

[menus]
  [[menus.main]]
    name = 'Contact'
    pageRef = '/post/contact'
    weight = 10
  
  [[menus.main]]
    name = 'GitHub'
    url = 'https://github.com/eri24816'
    weight = 20

  [[menus.main]]
    name = 'Spotify'
    url = 'https://open.spotify.com/artist/5XJx2SFNvzx61hF4OX3Z32?si=e91547d3fd2c4f59'
    weight = 30

  [[menus.main]]
    name = 'Resume'
    url = 'https://eri24816.tw/docs/resume241125.pdf'
    weight = 40
